fixed parentheses bug resulting in error
"W libqmlvideo_arm64-v8a.so: qrc:/main.qml:89: TypeError: Property
'toFixed' of object 724.992kb/s is not a function"
which was preventing display of metadata on android.

Strangely, and mysteriously, the broken code was working on Linux but not
Android.